version: '3'

services:
  php:
    container_name: cdpt_php
    build: docker/php-fpm
    ports:
      - 8000:8000
    volumes:
      - ./:/app
    working_dir: /app

  codeception:
    container_name: cdpt_codeception
    image: codeception/codeception
    volumes:
      - ./:/app
    working_dir: /app

  chrome:
    container_name: cdpts_chrome
    image: selenium/standalone-chrome-debug
    ports:
      - 5900
    environment:
      - no_proxy=localhost